extends: default

rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
