apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: loki-combined
  namespace: monitoring
spec:
  chain:
    middlewares:
      - name: loki-stripprefix
        namespace: monitoring
      - name: loki-redirect
        namespace: monitoring
