apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      vaultUrl: https://chai-homelab-kv.vault.azure.net
      tenantId: 9e8fdb32-cd60-4133-9918-3851cb11c34e
      authType: ServicePrincipal
      authSecretRef:
        clientId:
          name: azure-kv-creds
          namespace: eso-system
          key: clientId
        clientSecret:
          name: azure-kv-creds
          namespace: eso-system
          key: clientSecret
