---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: grafana-admin-creds
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana/admin
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin
        property: admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: alertmanager-discord-webhook
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: webhook-url
      remoteRef:
        key: discord/config
        property: webhook-url
