apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: health-checker
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: health-checker
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: webhook-url
      remoteRef:
        key: discord-webhook
